<?php 
$I = new AcceptanceTester($scenario);
$I->wantTo('ensure that everything work from CC01 document');
$I->amOnPage('/de/login/');
$I->fillField('input[name="email"]', 'testaccount@blacktri.com');
$I->fillField('input[name="password"]', 'password');
$I->click('Jetzt anmelden');
$I->wait(2);
$I->click('Hier klicken und den ersten Test anlegen');
$I->wait(2);
$I->see('Projekt erstellen');
$I->click('Visuellen A/B-Test erstellen');
$I->wait(2);
$I->see('URL angeben');
$I->fillField('input[name="vablpname"]', 'www.eckhardschneider.de/blacktritest/testpage_live.html');
$I->click('Visueller Editor');
$I->wait(2);
$I->switchToIFrame('frame_editor');
$webDriver = $I->executeInSelenium(function(\Facebook\WebDriver\Remote\RemoteWebDriver $webDriver) {
	return $webDriver;
});
$el = $webDriver->findElement(WebDriverBy::cssSelector('h1'));
$coords = $el->getLocation();
$x = $coords->getX();
$y = $coords->getY();
$I->switchToIFrame();
$I->moveMouseOver( '.editor_proxy > div.editor_proxy_scroll', $x  + 10, $y  + 10);
$webDriver->getMouse()->mouseMove(null, $x, $y)->click();
$I->wait(2);
$I->seeElement('#BTMouseOverEditorMenu');
$I->wait(2);
$I->click('Text bearbeiten');
$I->seeElement('#BTFactorEditPopup');
$I->executeJS('document.getElementById("textEditIframe").setAttribute("name", "textEditIframe")');
$I->switchToIframe('textEditIframe');
$I->executeJS('document.body.innerHTML="Alternative"');
$I->wait(2);
$I->switchToIframe();
$I->click('.BtEditorButton.ok');
$I->switchToIframe('frame_editor');
$I->wait(2);
$I->see('Alternative');
$I->switchToIframe();
$I->click('Segmentierung festlegen');
$I->wait(2);
$I->see('Segmentierung festlegen');
$I->click('Segmentierung abschließen');
$I->wait(2);
$I->see('Projektname und URL festlegen');
$I->fillField('input[name="testname"]', 'CC01');
$I->click('Konversionsziele festlegen');
$I->wait(2);
$I->see('Konversionsziele festlegen');
$I->click('Speichern und Projekt erstellen');
$I->wait(2);
$I->see('CC01 - Visueller A/B-Test');
$I->click('.variant_row_1 .icon a');
$handles=$webDriver->getWindowHandles();
$last_window = end($handles);
$webDriver->switchTo()->window($last_window);
$I->wait(2);
$I->see('Alternative');
