// <?php 
// $I = new AcceptanceTester($scenario);
// $I->wantTo('ensure that frontpage works');
// $I->amOnPage('/');
// $I->fillField("input[name='url']", 'http://www.eckhardschneider.de/blacktritest/testpage_live.html');
// $I->click('Ausprobieren');
// $I->wait(1);
// $I->switchToIFrame("frame_editor");
// $webDriver = $I->executeInSelenium(function(\Facebook\WebDriver\Remote\RemoteWebDriver $webDriver) {
// 	return $webDriver;
// });
// $el = $webDriver->findElement(WebDriverBy::cssSelector('h1'));
// $coords = $el->getLocation();
// $x = $coords->getX();
// $y = $coords->getY();
// $I->switchToIFrame();
// $I->moveMouseOver( '.editor_proxy > div.editor_proxy_scroll', $x  + 10, $y  + 10);
// $webDriver->getMouse()->mouseMove(null, $x, $y)->click();
// $I->wait(1);
// $I->seeElement('#BTMouseOverEditorMenu');
// $I->wait(1);
// $I->click('Text bearbeiten');
// $I->seeElement('#BTFactorEditPopup');
// $I->executeJS('document.getElementById("textEditIframe").setAttribute("name", "textEditIframe")');
// $I->switchToIframe('textEditIframe');
// $I->executeJS('document.body.innerHTML="Variant"');
// $I->wait(2);
// $I->switchToIframe();
// $I->click('.BtEditorButton.ok');
// $I->see('Variant');
// $I->wait(1);
